# # services/llm-service/config/model_configs.yaml

# models:
#   persian-llm:
#     model_path: "/app/models/farsi-llama-7b-instruct-v0.1"
#     model_type: "causal_lm"
#     language: "persian"
#     torch_dtype: "float16"
#     device_map: "auto"
#     load_in_8bit: false
#     load_in_4bit: false
#     trust_remote_code: true
#     max_memory_gb: 8
#     compile_model: false
#     use_flash_attention: false

#     # Generation settings
#     generation:
#       max_new_tokens: 512
#       temperature: 0.7
#       top_p: 0.9
#       top_k: 50
#       repetition_penalty: 1.1
#       length_penalty: 1.0
#       no_repeat_ngram_size: 3
#       do_sample: true
#       early_stopping: false

#     # Tokenizer settings
#     tokenizer:
#       padding_side: "left"
#       truncation_side: "left"
#       max_length: 2048

#   # Alternative models (can be added later)
#   persian-llm-large:
#     model_path: "/app/models/persian-large-model"
#     model_type: "causal_lm"
#     language: "persian"
#     torch_dtype: "float16"
#     device_map: "auto"
#     load_in_8bit: true
#     load_in_4bit: false
#     trust_remote_code: true
#     max_memory_gb: 16

#   embedding-model:
#     model_path: "/app/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
#     model_type: "embedding"
#     language: "multilingual"
#     torch_dtype: "float32"
#     device_map: "cpu"
#     max_memory_gb: 2

# # Service settings
# service:
#   host: "0.0.0.0"
#   port: 8002
#   workers: 1
#   max_concurrent_requests: 10
#   request_timeout: 300

#   # Cache settings
#   cache:
#     enabled: true
#     type: "redis"
#     url: "redis://redis:6379/2"
#     ttl: 3600
#     max_size: 1000

#   # Monitoring
#   monitoring:
#     enabled: true
#     metrics_port: 8003
#     log_level: "INFO"

#   # Security
#   security:
#     api_key_required: false
#     rate_limit:
#       enabled: true
#       requests_per_minute: 60
#       burst_size: 10

# # Hardware optimization
# hardware:
#   gpu:
#     enabled: true
#     memory_fraction: 0.9
#     allow_growth: true

#   cpu:
#     num_threads: 4
#     use_openmp: true

#   memory:
#     swap_enabled: false
#     memory_mapping: true
